In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'Age': [25, 32, np.nan, 28, 45, 38, np.nan, 22, 41, 36],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'HR', 'Finance', 'IT'],
    'Salary': [50000, 60000, 55000, 58000, 72000, 68000, 59000, 47000, 71000, 65000],
    'Bonus%': [5, 10, np.nan, 0, 15, 8, 12, np.nan, 20, 0],
    'JoiningMonth': ['January', 'March', 'February', 'January', 'April', 'March', 'January', 'May', 'June', 'January']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   EmployeeID     Name   Age Department  Salary  Bonus% JoiningMonth
0         101    Alice  25.0         HR   50000     5.0      January
1         102      Bob  32.0         IT   60000    10.0        March
2         103  Charlie   NaN    Finance   55000     NaN     February
3         104    David  28.0         IT   58000     0.0      January
4         105      Eva  45.0         HR   72000    15.0        April
5         106    Frank  38.0    Finance   68000     8.0        March
6         107    Grace   NaN         IT   59000    12.0      January
7         108   Hannah  22.0         HR   47000     NaN          May
8         109      Ian  41.0    Finance   71000    20.0         June
9         110     Jack  36.0         IT   65000     0.0      January

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EmployeeID    10 non-null     int64
 1   Name          10 non-null     object
 2   Age           8 non-null      float64
 3   Department    10 non-null     object
 4   Salary        10 non-null     int64
 5   Bonus%        8 non-null      float64
 6   JoiningMonth  10 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 692.0+ bytes

In [6]:
df.describe()

       EmployeeID        Age       Salary     Bonus%
count    10.00000   8.000000     10.00000   8.000000
mean    105.50000  33.375000  60500.00000   8.750000
std       3.02765   8.034524   8501.63383   7.025464
min     101.00000  22.000000  47000.00000   0.000000
25%     103.25000  27.250000  55750.00000   3.750000
50%     105.50000  34.000000  59500.00000   9.000000
75%     107.75000  38.750000  67250.00000  12.750000
max     110.00000  45.000000  72000.00000  20.000000

In [7]:
df.isnull().sum()

EmployeeID      0
Name            0
Age             2
Department      0
Salary          0
Bonus%          2
JoiningMonth    0
dtype: int64

In [8]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

C:\Users\Shahzaib\AppData\Local\Temp\ipykernel_9300\1698716155.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

In [9]:
df

   EmployeeID     Name     Age Department  Salary  Bonus% JoiningMonth
0         101    Alice  25.000         HR   50000     5.0      January
1         102      Bob  32.000         IT   60000    10.0        March
2         103  Charlie  33.375    Finance   55000     NaN     February
3         104    David  28.000         IT   58000     0.0      January
4         105      Eva  45.000         HR   72000    15.0        April
5         106    Frank  38.000    Finance   68000     8.0        March
6         107    Grace  33.375         IT   59000    12.0      January
7         108   Hannah  22.000         HR   47000     NaN          May
8         109      Ian  41.000    Finance   71000    20.0         June
9         110     Jack  36.000         IT   65000     0.0      January

In [10]:
df['Bonus%'].replace(np.nan, df['Bonus%'].mean(), inplace=True)

C:\Users\Shahzaib\AppData\Local\Temp\ipykernel_9300\4031077901.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Bonus%'].replace(np.nan, df['Bonus%'].mean(), inplace=True)

In [11]:
df

   EmployeeID     Name     Age Department  Salary  Bonus% JoiningMonth
0         101    Alice  25.000         HR   50000    5.00      January
1         102      Bob  32.000         IT   60000   10.00        March
2         103  Charlie  33.375    Finance   55000    8.75     February
3         104    David  28.000         IT   58000    0.00      January
4         105      Eva  45.000         HR   72000   15.00        April
5         106    Frank  38.000    Finance   68000    8.00        March
6         107    Grace  33.375         IT   59000   12.00      January
7         108   Hannah  22.000         HR   47000    8.75          May
8         109      Ian  41.000    Finance   71000   20.00         June
9         110     Jack  36.000         IT   65000    0.00      January

In [12]:
df.loc[(df['Bonus%'] == 0), 'GetBonus'] = 'No'
df.loc[(df['Bonus%'] > 0), 'GetBonus'] = 'Yes'

In [13]:
df.loc[(df['Age'] <= 25), 'AgeGroup'] = 'Young'
df.loc[(df['Age'] > 25) & (df['Age'] < 40), 'AgeGroup'] = 'Mid Age'
df.loc[(df['Age'] >= 40), 'AgeGroup'] = 'Senior'

In [14]:
df

,EmployeeID,Name,Age,Department,Salary,Bonus%,JoiningMonth,GetBonus,AgeGroup
0,101,Alice,25.000,HR,50000,5.00,January,Yes,Young
1,102,Bob,32.000,IT,60000,10.00,March,Yes,Mid Age
2,103,Charlie,33.375,Finance,55000,8.75,February,Yes,Mid Age
3,104,David,28.000,IT,58000,0.00,January,No,Mid Age
4,105,Eva,45.000,HR,72000,15.00,April,Yes,Senior
5,106,Frank,38.000,Finance,68000,8.00,March,Yes,Mid Age
6,107,Grace,33.375,IT,59000,12.00,January,Yes,Mid Age
7,108,Hannah,22.000,HR,47000,8.75,May,Yes,Young
8,109,Ian,41.000,Finance,71000,20.00,June,Yes,Senior
9,110,Jack,36.000,IT,65000,0.00,January,No,Mid Age

In [15]:
def slice_month(value):
    return value[:3]

In [31]:
df['JoiningMonth'] = df['JoiningMonth'].map(slice_month)

In [36]:
df['Age'] = df['Age'].astype(int)

In [37]:
df

,EmployeeID,Name,Age,Department,Salary,Bonus%,JoiningMonth,GetBonus,AgeGroup
0,101,Alice,25,HR,50000,5.00,Jan,Yes,Young
1,102,Bob,32,IT,60000,10.00,Mar,Yes,Mid Age
2,103,Charlie,33,Finance,55000,8.75,Feb,Yes,Mid Age
3,104,David,28,IT,58000,0.00,Jan,No,Mid Age
4,105,Eva,45,HR,72000,15.00,Apr,Yes,Senior
5,106,Frank,38,Finance,68000,8.00,Mar,Yes,Mid Age
6,107,Grace,33,IT,59000,12.00,Jan,Yes,Mid Age
7,108,Hannah,22,HR,47000,8.75,May,Yes,Young
8,109,Ian,41,Finance,71000,20.00,Jun,Yes,Senior
9,110,Jack,36,IT,65000,0.00,Jan,No,Mid Age

In [41]:
gp1  = df.groupby(['Department', 'Name']).agg({'Salary': 'sum'})

In [42]:
gp1

                    Salary
Department Name
Finance    Charlie   55000
           Frank     68000
           Ian       71000
HR         Alice     50000
           Eva       72000
           Hannah    47000
IT         Bob       60000
           David     58000
           Grace     59000
           Jack      65000